options:
  cache-config: true
  formatter: stylish
  merge-default-rules: false

files:
  include: 'styles/**/*.scss'

rules:
  attribute-quotes: 2
  brace-style:
    - 2
    -
      style: 1tbs
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false
  class-name-format:
    - 0
    -
      allow-leading-underscore: false
      convention: ^([a-zA-Z]*)-(([a-zA-Z]*)+)(__(([a-zA-Z0-9]+)+))?(--(([a-zA-Z0-9])+)+)?$
      convention-explanation: 'Class name does not follow conventions: .luna-[className][__descendantName][--modifierName], .u-utilityName, or .is-stateName'
  empty-args:
    - 2
    -
      include: true
  empty-line-between-blocks:
    - 2
    -
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: camelcase
  hex-length:
    - 2
    -
      style: short
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: true
  nesting-depth:
    - 2
    -
      max-depth: 3
  no-attribute-selectors: 0
  no-color-keywords: 2
  no-css-comments: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors:
    - 2
    -
      whitelist:
        - '%checkRadio'
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-vendor-prefixes: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  property-sort-order: 2
  quotes: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  zero-unit: 2
